[package]
edition = "2021"
name    = "rome_v8"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow   = "1.0.57"
serde    = "1.0.33"
serde_v8 = { version = "0.65.0" }
v8       = { version = "0.51.0", default-features = false }

rome_js_factory = { workspace = true }
rome_js_syntax  = { workspace = true }
rome_rowan      = { workspace = true, features = ["serde"] }

[dev-dependencies]
bpaf             = { workspace = true }
crossbeam        = "0.8.2"
rome_console     = { workspace = true }
rome_diagnostics = { workspace = true }
rome_fs          = { workspace = true }
rome_js_parser   = { workspace = true }
rome_service     = { workspace = true }

[build-dependencies]
rome_idl = { path = "../rome_idl" }
